config/routes.rb
IntelDemoSummer2013::Application.routes.draw do
  resources :wks
  match '/configuration' => 'Wks#configuration'
  get '/network_info' => 'Wks#network_info'
  get '/network_init' => 'Wks#network_init'
  post '/status_update' => 'Wks#status_update'

  root :to => 'Wks#index'

end

app/models/state.rb
class State < ActiveRecord::Base
  # attr_accessible :title, :body
  self.table_name = 'state'
end

app/models/wk.rb
class Wk < ActiveRecord::Base
  # attr_accessible :title, :body
  self.table_name = 'wk'
end

app/models/wk_initialize.rb
class Wk_initialize < ActiveRecord::Base
  self.table_name = 'wk_initialize'
end

app/models/wukong.rb
class Wukong < ActiveRecord::Base
  attr_accessible :status, :region1, :region2, :region3, :region4, :region5, :region6, :region7, :region8, :region9, :region10,
    :region11, :region12, :region13, :region14, :region15, :region16
  self.table_name = 'wukong'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/wks_controller.rb
class WksController < ApplicationController

  def status_update
    require 'json'
    values = params["wukong_status"].gsub("'", "\"").gsub(/"\z/, "").gsub(/\A"/, "").gsub(/u"/, "\"")
    logger.info values
    data = JSON.parse(values)
    logger.info data
    wukong = Wukong.create(data)
    render nothing: true, status: :ok
  end

  def network_init
    res = Wk_initialize.all.to_a

    respond_to do |format|
      format.json { render json: res }
      format.xml { render xml: res.to_xml(root: :nodes) }
    end
  end

  def network_info
    n = 1
    @nodes = []
    time = Wk.last.time
    while Wk.exists?
      new_node = Wk.last(n).first
      break if new_node.time != time
      @nodes << new_node
      n += 1
    end

    res = @nodes

    respond_to do |format|
      format.json { render json: res }
      format.xml { render xml: res.to_xml(root: :nodes) }
    end
  end

  def configuration
    min_version = params[:id]
    @state = State.find_by_id(min_version) if min_version.present?
    @last_state = State.last
    need_update = @state ? @state.id < @last_state.id : true

    res = {update: need_update, state: @last_state}

    respond_to do |format|
      format.json { render json: res }
      format.xml { render xml: res.to_xml(root: :wukong) }
    end
  end

  # GET /wks
  # GET /wks.json
  def index
    @wks = Wk.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @wks }
    end
  end

  # GET /wks/1
  # GET /wks/1.json
  def show
    @wk = Wk.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @wk }
    end
  end

  # GET /wks/new
  # GET /wks/new.json
  def new
    @wk = Wk.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @wk }
    end
  end

  # GET /wks/1/edit
  def edit
    @wk = Wk.find(params[:id])
  end

  # POST /wks
  # POST /wks.json
  def create
    @wk = Wk.new(params[:wk])

    respond_to do |format|
      if @wk.save
        format.html { redirect_to @wk, notice: 'Wk was successfully created.' }
        format.json { render json: @wk, status: :created, location: @wk }
      else
        format.html { render action: "new" }
        format.json { render json: @wk.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /wks/1
  # PUT /wks/1.json
  def update
    @wk = Wk.find(params[:id])

    respond_to do |format|
      if @wk.update_attributes(params[:wk])
        format.html { redirect_to @wk, notice: 'Wk was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @wk.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wks/1
  # DELETE /wks/1.json
  def destroy
    @wk = Wk.find(params[:id])
    @wk.destroy

    respond_to do |format|
      format.html { redirect_to wks_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/wks_helper.rb
module WksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IntelDemoSummer2013</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/wks/_form.html.erb
<%= form_for(@wk) do |f| %>
  <% if @wk.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wk.errors.count, "error") %> prohibited this wk from being saved:</h2>

      <ul>
      <% @wk.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/wks/edit.html.erb
<h1>Editing wk</h1>

<%= render 'form' %>

<%= link_to 'Show', @wk %> |
<%= link_to 'Back', wks_path %>

app/views/wks/index.html.erb
<h1>Listing wks</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @wks.each do |wk| %>
  <tr>
    <td><%= link_to 'Show', wk %></td>
    <td><%= link_to 'Edit', edit_wk_path(wk) %></td>
    <td><%= link_to 'Destroy', wk, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Wk', new_wk_path %>

app/views/wks/new.html.erb
<h1>New wk</h1>

<%= render 'form' %>

<%= link_to 'Back', wks_path %>

app/views/wks/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_wk_path(@wk) %> |
<%= link_to 'Back', wks_path %>